In [1]:
import numpy as np

In [3]:
np.linspace(10, 20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [4]:
# uniform distribution [0, 1]
random_array = np.random.rand(3, 2)

random_array

array([[0.81087391, 0.36405677],
       [0.46218499, 0.25705145],
       [0.21969252, 0.8944096 ]])

In [5]:
# standard normal distribution (mean 0, varaince 1)
random_array = np.random.randn(3, 2)

random_array

array([[-1.0617451 ,  1.41907314],
       [ 0.14520406,  1.18365603],
       [ 0.7856577 , -0.82364682]])

In [6]:
random_array.mean()

0.2746998361026644

In [8]:
random_integers = np.random.randint(11, 33, size=(4, 5))
random_integers

array([[31, 21, 27, 21, 11],
       [21, 23, 20, 15, 19],
       [18, 32, 23, 26, 29],
       [26, 13, 29, 23, 29]])

In [10]:
list_a = [22, 67, 89, 11, 43, 90, 12, 44, 32, 67, 51]

sample = np.random.choice(list_a)
sample

44

In [11]:
list_a = [22, 67, 89, 11, 43, 90, 12, 44, 32, 67, 51]

sample = np.random.choice(list_a, size=3)
sample

array([89, 90, 43])

In [13]:
uniform_sample = np.random.uniform(1.0, 3.0, size=5)
uniform_sample

array([1.19679904, 2.83437187, 2.84387079, 1.80658842, 1.78750039])

In [14]:
random_integers = np.random.randint(10, 90, size=(4, 5))
random_integers

array([[78, 15, 48, 69, 31],
       [82, 66, 40, 17, 87],
       [20, 74, 85, 23, 64],
       [16, 49, 21, 25, 17]])

In [15]:
random_integers = np.random.randint(10, 90, size=(4, 5))
random_integers

array([[27, 24, 89, 10, 64],
       [38, 20, 61, 60, 36],
       [46, 22, 60, 47, 62],
       [19, 53, 78, 78, 29]])

In [16]:
np.random.seed(30)  # seed for reproducibility 
random_integers = np.random.randint(10, 90, size=(4, 5))
random_integers

array([[47, 47, 55, 55, 22],
       [33, 12, 63, 27, 56],
       [13, 51, 17, 75, 59],
       [55, 71, 45, 28, 28]])

In [17]:
np.random.seed(30)  # seed for reproducibility 
random_integers = np.random.randint(10, 90, size=(4, 5))
random_integers

array([[47, 47, 55, 55, 22],
       [33, 12, 63, 27, 56],
       [13, 51, 17, 75, 59],
       [55, 71, 45, 28, 28]])

In [20]:
# attach probability 
n_samples = 15
education = np.random.choice([0, 1, 2, 3], n_samples, p = [0.2, 0.5, 0.25, 0.05])
education

array([1, 1, 2, 2, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1])